trigger:
- main

parameters:
  - name: services
    type: object
    default:
      - api
      - web


pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    strategy:
      matrix:
        API:
          service: 'api'
        WEB:
          service: 'web'
    steps:
    - script: echo ${{ service }}
