
parameters:
  - name: services
    type: object
    default:
      - api
      - web
  - name: tags
    type: object

jobs:
  - job: Build
    displayName: Build
    strategy:
      maxParallel: 2
      matrix:
        ${{ each service in parameters.services }}:
          ${{ service }}-service:
            serviceName: ${{ service }}
    steps:
      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
          command: login
          containerRegistry: dockerHubRegistryPrimary
      - task: Docker@2
        displayName: Build and Push Docker Images
        inputs:
          command: buildAndPush
          containerRegistry: dockerHubRegistryPrimary
          Dockerfile: services/$(serviceName)/Dockerfile.k8s
          buildContext: services/$(serviceName)
          repository: azuredevtest/$(serviceName)
          tags: |
            ${{ each tag in parameters.tags }}
              ${{ tag }}
