parameters:
  - name: environment
    type: string
    values:
      - dev1
      - dev2
      - staging
      - production

jobs:
  - deployment: Deploy
    displayName: Deploy Services
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo Deploy API service
              displayName: Deploy API service
            - script: echo Deploy Web service
              displayName: Deploy Web service
