trigger:
  - main

pool:
  name: default
  demands: agent.os -equals Linux

stages:
  - stage: UnitTest
    displayName: Unit Test
    jobs:
      - job: Execute
        steps:
          - bash: echo "Run Unit Test!"
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: Build
        strategy:
          maxParallel: 2
          matrix:
            api-service:
              service: api
            web-service:
              service: web
        container: ubuntu:18.04
        steps:
          - script: echo Build and Push Docker Image $(service)


