trigger:
  - main

stages:
  - stage: Unit Test
    jobs:
      - job: Execute
        steps:
          - bash: echo "Run Unit Test!"
  - stage: Build and Push Docker Image
    jobs:
      - job: Build
        strategy:
          maxParallel: 2
          matrix:
            api-service:
              service: api
            web-service:
              service: web
        steps:
          - script: echo Build and Push Docker Image $(service)


