trigger:
  - dev2

variables:
  - name: buildDate
    value: $[format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime)]

pool:
  name: default
  demands: agent.os -equals Linux

stages:
  - stage: Build
    displayName: Build artifacts for dev2
    jobs:
      - template: templates/build-pipeline.yaml
        parameters:
          buildDate: $(buildDate)
  
  - stage: Deploy
    displayName: Deploy to dev2 environment
    condition: succeeded()
    dependsOn: Build
    jobs:
      - template: templates/deployment-pipeline.yaml
        parameters:
          environment: dev2
