trigger:
  branches:
    include:
      - dev1
      - dev2

variables:
  - name: buildDate
    value: $[format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime)]

pool:
  name: default
  demands: agent.os -equals Linux

stages:
  - stage: Build
    displayName: Build Services
    jobs:
      - template: pipelines-build-template.yaml
        parameters:
          buildDate: buildDate
  
  - stage: DeployDev1
    displayName: Deploy to dev1 environment
    condition: succeeded()
    dependsOn: Build
    jobs:
      - template: pipelines-deployment-template.yaml
        parameters:
          environment: dev1
  
  - stage: DeployDev2
    displayName: Deploy to dev2 environment
    condition: succeeded()
    dependsOn: Build
    jobs:
      - template: pipelines-deployment-template.yaml
        parameters:
          environment: dev2



