trigger:
  branches:
    include:
      - dev1
      - dev2

pool:
  name: default
  demands: agent.os -equals Linux

stages:
  - stage: Build
    displayName: Build Services
    jobs:
      - template: pipelines-build-template.yaml
  
  - stage: DeployDev1
    displayName: Deploy to dev1 environment
    condition: succedded()
    dependsOn: Build
    jobs:
      - template: pipelines-deployment-template.yaml
        parameters:
          environment: dev1
  
  - stage: DeployDev2
    displayName: Deploy to dev2 environment
    condition: succedded()
    dependsOn: Build
    jobs:
      - template: pipelines-deployment-template.yaml
        parameters:
          environment: dev2



