trigger:
  - feature/*

variables:
  - name: buildDate
    value: $[format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime)]

pool:
  name: default
  demands: agent.os -equals Linux

stages:
  - stage: Build
    displayName: Building $(Build.SourceBranchName)
    jobs:
      - template: templates/build-pipeline.yaml
        parameters:
          tags: $(Build.SourceBranchName)
