trigger:
  - main

variables:
  - name: buildDate
    value: $[format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime)]

pool:
  name: default
  demands: agent.os -equals Linux

stages:
  - stage: Build
    displayName: Build artifacts for release
    jobs:
      - template: templates/build-pipeline.yaml
        parameters:
          tags: $(Build.SourceBranchName)-$(buildDate).$(Build.BuildId)

  - stage: DeployStaging
    displayName: Deploy to staging environment
    condition: succeeded()
    dependsOn: Build
    jobs:
      - template: templates/deployment-pipeline.yaml
        parameters:
          environment: staging

  - stage: DeployProduction
    displayName: Deploy to production environment
    condition: succeeded('DeployStaging')
    dependsOn:
      - Build
      - DeployStaging
    jobs:
      - template: templates/deployment-pipeline.yaml
        parameters:
          environment: production
