trigger:
  - releases/*

variables:
  - name: buildDate
    value: $[format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime)]
  
pool:
  name: default
  demands: agent.os -equals Linux

stages:
  - stage: Build
    displayName: Build artifacts for release
    jobs:
      - template: templates/build-pipeline.yaml
        parameters:
          tags: $(Build.SourceBranchName)
      - job: GithubRelease
        displayName: Create Github Release
        condition: succeeded()
        steps:
          - task: GitHubRelease@0
            displayName: Create Release
            inputs:
              gitHubConnection: github-sajalshres
              repositoryName: sajalshres/azure-devops-test
              tagSource: manual
              tag: $(Build.SourceBranchName)
        
