apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: azure-devops-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: sajalshres/azure-devops-test/api:_TAG
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 8000
              name: api
          envFrom:
            - secretRef:
                name: envs-secret
